In [ ]:
# get US gdp
# get political parties
# get second derivative of gdp growth
# get coreelation with parties

# OECD

In [1]:
!pip install pandasdmx

Collecting pandasdmx
  Downloading https://files.pythonhosted.org/packages/e7/5d/7e29616b0376d0a15eb3013c909c4e9021b6c6e244ef1b48817b4d0c4d46/pandaSDMX-0.9-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 4.1MB/s ta 0:00:011
Requirement already satisfied: lxml in ./notebooks/lib/python3.6/site-packages (from pandasdmx) (4.2.5)
Requirement already satisfied: pandas in ./notebooks/lib/python3.6/site-packages (from pandasdmx) (0.23.4)
Collecting jsonpath-rw (from pandasdmx)
  Downloading https://files.pythonhosted.org/packages/71/7c/45001b1f19af8c4478489fbae4fc657b21c4c669d7a5a036a86882581d85/jsonpath-rw-1.4.0.tar.gz
Requirement already satisfied: requests in ./notebooks/lib/python3.6/site-packages (from pandasdmx) (2.21.0)
Requirement already satisfied: setuptools in ./notebooks/lib/python3.6/site-packages (from pandasdmx) (40.6.2)
Requirement already satisfied: pytz>=2011k in ./notebooks/lib/python3.6/site-packages (from pandas->pandasdmx) (2018.7)
Requirement already satisfied: python-dateutil>=2.5.0 in ./notebooks/lib/python3.6/site-packages (from pandas->pandasdmx) (2.7.5)
Requirement already satisfied: numpy>=1.9.0 in ./notebooks/lib/python3.6/site-packages (from pandas->pandasdmx) (1.15.4)
Collecting ply (from jsonpath-rw->pandasdmx)
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 7.5MB/s ta 0:00:011
Requirement already satisfied: decorator in ./notebooks/lib/python3.6/site-packages (from jsonpath-rw->pandasdmx) (4.3.2)
Requirement already satisfied: six in ./notebooks/lib/python3.6/site-packages (from jsonpath-rw->pandasdmx) (1.11.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./notebooks/lib/python3.6/site-packages (from requests->pandasdmx) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./notebooks/lib/python3.6/site-packages (from requests->pandasdmx) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./notebooks/lib/python3.6/site-packages (from requests->pandasdmx) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in ./notebooks/lib/python3.6/site-packages (from requests->pandasdmx) (2.8)
Building wheels for collected packages: jsonpath-rw
  Running setup.py bdist_wheel for jsonpath-rw ... done
  Stored in directory: /Users/jordanvalansi/Library/Caches/pip/wheels/5c/00/9a/82822db383c2d96dcebf839786665a185f92d37e5026f9806f
Successfully built jsonpath-rw
Installing collected packages: ply, jsonpath-rw, pandasdmx
Successfully installed jsonpath-rw-1.4.0 pandasdmx-0.9 ply-3.11
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
from pandasdmx import Request

In [8]:
oecd = Request('OECD')

In [10]:
data_response = oecd.data(resource_id='SNA_TABLE1_SNA93', key='all?startTime=2005')

In [12]:
df = data_response.write(data_response.data.series, parse_time=False)

/Users/jordanvalansi/projects/notebooks/notebooks/lib/python3.6/site-packages/pandasdmx/writer/data2pandas.py:124: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  d_frame = PD.concat(list(pd_series), axis=1, copy=False)

In [13]:
df

LOCATION        AUS                                                         \
TRANSACT      B1_GA
MEASURE           C          V            CXC         VXCOB            CPC
2005       967454.0  1012269.0  738813.413060  8.874422e+05  696834.348269
2006      1045674.0  1045674.0  787422.908650  9.591931e+05  744417.896257
2007      1132172.0  1084156.0  947368.773377  1.038537e+06  792988.794850
2008            NaN        NaN            NaN           NaN            NaN
2009            NaN        NaN            NaN           NaN            NaN
2010            NaN        NaN            NaN           NaN            NaN
2011            NaN        NaN            NaN           NaN            NaN
2012            NaN        NaN            NaN           NaN            NaN
2013            NaN        NaN            NaN           NaN            NaN
2014            NaN        NaN            NaN           NaN            NaN
2015            NaN        NaN            NaN           NaN            NaN

LOCATION                                                               \
TRANSACT                 P51PI66
MEASURE           VPCOB        C        V           CXC         VXCOB
2005      642971.198316  15146.3  15146.3  11566.740742  13893.648639
2006      694956.312991      NaN      NaN           NaN           NaN
2007      752442.997332      NaN      NaN           NaN           NaN
2008                NaN      NaN      NaN           NaN           NaN
2009                NaN      NaN      NaN           NaN           NaN
2010                NaN      NaN      NaN           NaN           NaN
2011                NaN      NaN      NaN           NaN           NaN
2012                NaN      NaN      NaN           NaN           NaN
2013                NaN      NaN      NaN           NaN           NaN
2014                NaN      NaN      NaN           NaN           NaN
2015                NaN      NaN      NaN           NaN           NaN

LOCATION      ...                GRC                                          \
TRANSACT      ...            P51PI63
MEASURE       ...                XVP         VPVOB           PVP       VIXOB
2005          ...        6819.025305   8585.879678   7898.693720   81.507353
2006          ...        9311.837031  11879.309417  10486.624864  112.772495
2007          ...       12969.963263  16377.722249  14795.386526  155.476765
2008          ...       10884.990866  12590.511775  11067.359513  119.524071
2009          ...        9734.583975  10184.299856   9479.974786   96.681453
2010          ...       10249.657317  10533.871282  10578.385189  100.000000
2011          ...        7993.378534   8600.258982   8600.258982   81.643859
2012          ...        5984.958748   6109.463536   6148.958815   57.998274
2013          ...        5586.123662   6231.913872   6323.178753   59.160718
2014          ...                NaN           NaN           NaN         NaN
2015          ...                NaN           NaN           NaN         NaN

LOCATION                                                                      \
TRANSACT
MEASURE          DOB            VP           CXC         VXCOB           CPC
2005       89.820062   5339.000000   6730.215496   7167.653431   7579.304162
2006       89.955704   7487.834393   9407.547911   9932.046632  10731.588423
2007       90.010931  10338.889484  14159.182746  13701.483969  14396.407658
2008       92.984066   7952.987956  12034.542963  10881.048967  11719.778076
2009       99.808479   6645.557115   9909.517663   9447.512298  10227.336547
2010      100.000000   7378.144072   9790.544769   9790.544769  10533.871282
2011      100.417560   6035.360495   8424.994260   8026.755685   8655.856273
2012       99.412524   4305.310000   5476.362403   5644.988047   6198.935162
2013       99.506334   4347.646530   5777.995297   5763.562649   6751.455165
2014             NaN           NaN           NaN           NaN           NaN
2015             NaN           NaN           NaN           NaN           NaN

LOCATION
TRANSACT
MEASURE          VPCOB
2005       7711.842438
2006      10686.116376
2007      14741.740313
2008      11707.169717
2009      10164.794793
2010      10533.871282
2011       8636.170223
2012       6073.571888
2013       6201.149017
2014               NaN
2015               NaN

[11 rows x 32491 columns]

In [ ]:
https://stats.oecd.org/SDMX-JSON/data/SNA_TABLE1_SNA93/AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EA17+EU28+NMEC+CHN+COL+IND+IDN+RUS+ZAF+FRME+DEW.B1_GA+B1G_P119+B1G+B1GA_B+B1GC_E+B1GD+B1GF+B1GG_I+B1GJ_K+B1GL_P+B1GVA+B1GVB_E+B1GVC+B1GVF+B1GVG_I+B1GVJ+B1GVK+B1GVL+B1GVM_N+B1GVO_Q+B1GVR_U+P119+D21_D31+D21S1+D31S1+DB1_GA+B1_GE+P3_P5+P3+P31S14_S15+P31S14+P31S15+P3S13+P31S13+P32S13+P41+P5+P51+P51PI61+P51PI62+P51PI63+P51PI64+P51PI65+P51PI66+P51N1111+P51N1112+P51N1113+P51N11131+P51N11132+P51N1114+P51N112+P52_P53+P52+P53+B11+P6+P61+P62+P7+P71+P72+DB1_GE+B1_GI+D1+D1A_B+D1C_E+D1D+D1F+D1G_I+D1J_K+D1L_P+D1VA+D1VB_E+D1VC+D1VF+D1VG_I+D1VJ+D1VK+D1VL+D1VM_N+D1VO_Q+D1VR_U+D11+D11A_B+D11C_E+D11D+D11F+D11G_I+D11J_K+D11L_P+D11VA+D11VB_E+D11VC+D11VF+D11VG_I+D11VJ+D11VK+D11VL+D11VM_N+D11VO_Q+D11VR_U+B2G_B3G+D2_D3+D2S1+D3S1+DB1_GI.C+V+VP+VOB+CXC+VXCOB+VXVOB+XVP+CPC+VPCOB+VPVOB+PVP+HCXC+HVXVOB+HCPC+HVPVOB+HCPIXOE+VIXOB+DOB+G/all?startTime=2005&endTime=2013&dimensionAtObservation=allDimensions

# World Bank data

In [18]:
!pip install pandas_datareader

Collecting pandas_datareader
  Using cached https://files.pythonhosted.org/packages/cc/5c/ea5b6dcfd0f55c5fb1e37fb45335ec01cceca199b8a79339137f5ed269e0/pandas_datareader-0.7.0-py2.py3-none-any.whl
Collecting wrapt (from pandas_datareader)
Requirement already satisfied: lxml in ./notebooks/lib/python3.6/site-packages (from pandas_datareader) (4.2.5)
Requirement already satisfied: requests>=2.3.0 in ./notebooks/lib/python3.6/site-packages (from pandas_datareader) (2.21.0)
Requirement already satisfied: pandas>=0.19.2 in ./notebooks/lib/python3.6/site-packages (from pandas_datareader) (0.23.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./notebooks/lib/python3.6/site-packages (from requests>=2.3.0->pandas_datareader) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./notebooks/lib/python3.6/site-packages (from requests>=2.3.0->pandas_datareader) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./notebooks/lib/python3.6/site-packages (from requests>=2.3.0->pandas_datareader) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./notebooks/lib/python3.6/site-packages (from requests>=2.3.0->pandas_datareader) (3.0.4)
Requirement already satisfied: python-dateutil>=2.5.0 in ./notebooks/lib/python3.6/site-packages (from pandas>=0.19.2->pandas_datareader) (2.7.5)
Requirement already satisfied: numpy>=1.9.0 in ./notebooks/lib/python3.6/site-packages (from pandas>=0.19.2->pandas_datareader) (1.15.4)
Requirement already satisfied: pytz>=2011k in ./notebooks/lib/python3.6/site-packages (from pandas>=0.19.2->pandas_datareader) (2018.7)
Requirement already satisfied: six>=1.5 in ./notebooks/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.19.2->pandas_datareader) (1.11.0)
Installing collected packages: wrapt, pandas-datareader
Successfully installed pandas-datareader-0.7.0 wrapt-1.11.1
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [19]:
from pandas_datareader import wb

In [31]:
gdp = wb.search('gdp')

In [32]:
gdp.head()

,id,name,source,sourceNote,sourceOrganization,topics,unit
641,5.51.01.10.gdp,Per capita GDP growth,Statistical Capacity Indicators,GDP per capita is the sum of gross value added...,b'World Development Indicator (WDI) databank. ...,,
643,6.0.GDP_current,GDP (current $),LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth,
644,6.0.GDP_growth,GDP growth (annual %),LAC Equity Lab,Annual percentage growth rate of GDP at market...,b'World Development Indicators (World Bank)',Economy & Growth,
645,6.0.GDP_usd,GDP (constant 2005 $),LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth,
646,6.0.GDPpc_constant,"GDP per capita, PPP (constant 2011 internation...",LAC Equity Lab,GDP per capita based on purchasing power parit...,b'World Development Indicators (World Bank)',Economy & Growth,

In [36]:
gdp[gdp['name'].apply(lambda x: x.startswith('GDP'))]

,id,name,source,sourceNote,sourceOrganization,topics,unit
643,6.0.GDP_current,GDP (current $),LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth,
644,6.0.GDP_growth,GDP growth (annual %),LAC Equity Lab,Annual percentage growth rate of GDP at market...,b'World Development Indicators (World Bank)',Economy & Growth,
645,6.0.GDP_usd,GDP (constant 2005 $),LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth,
646,6.0.GDPpc_constant,"GDP per capita, PPP (constant 2011 internation...",LAC Equity Lab,GDP per capita based on purchasing power parit...,b'World Development Indicators (World Bank)',Economy & Growth,
4895,EG.GDP.PUSE.KO.87,GDP per unit of energy use (1987 US$ per kg of...,WDI Database Archives,,b'',,
4896,EG.GDP.PUSE.KO.KD,GDP per unit of energy use (2000 US$ per kg of...,WDI Database Archives,,b'',,
4897,EG.GDP.PUSE.KO.PP,GDP per unit of energy use (PPP $ per kg of oi...,World Development Indicators,GDP per unit of energy use is the PPP GDP per ...,b'IEA Statistics OECD/IEA 2014 (http://www.ie...,Energy & Mining,
4898,EG.GDP.PUSE.KO.PP.KD,GDP per unit of energy use (constant 2011 PPP ...,World Development Indicators,GDP per unit of energy use is the PPP GDP per ...,b'IEA Statistics OECD/IEA 2014 (http://www.ie...,Energy & Mining,
5075,EU.EGY.USES.GDP,GDP per unit of energy use (1987 US$ per kg of...,WDI Database Archives,,b'',,
8008,NA.GDP.AGR.CR,"GDP on Agriculture Sector (in IDR Million), Cu...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8009,NA.GDP.AGR.KR,"GDP on Agriculture Sector (in IDR Million), Co...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8010,NA.GDP.CNST.CR,"GDP on Construction Sector (in IDR Million), C...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8011,NA.GDP.CNST.KR,"GDP on Construction Sector (in IDR Million), C...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8014,NA.GDP.FINS.CR,GDP on Financial Service Sector (in IDR Millio...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8015,NA.GDP.FINS.KR,GDP on Financial Service Sector (in IDR Millio...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8018,NA.GDP.MINQ.CR,GDP on Mining and Quarrying Sector (in IDR Mil...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8019,NA.GDP.MINQ.KR,GDP on Mining and Quarrying Sector (in IDR Mil...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8020,NA.GDP.MNF.CR,"GDP on Manufacturing Sector (in IDR Million), ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8021,NA.GDP.MNF.KR,"GDP on Manufacturing Sector (in IDR Million), ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8022,NA.GDP.SRV.OTHR.CR,"GDP on Other Service Sector (in IDR Million), ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8023,NA.GDP.SRV.OTHR.KR,"GDP on Other Service Sector (in IDR Million), ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8024,NA.GDP.TRAN.COMM.CR,GDP on Transportation and Telecommunication Se...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8025,NA.GDP.TRAN.COMM.KR,GDP on Transportation and Telecommunication Se...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8026,NA.GDP.TRD.HTL.CR,"GDP on Trade, Hotel and Restaurant Sector (in ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8027,NA.GDP.TRD.HTL.KR,"GDP on Trade, Hotel and Restaurant Sector (in ...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8028,NA.GDP.UTL.CR,"GDP on Utilities Sector (in IDR Million), Curr...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8029,NA.GDP.UTL.KR,"GDP on Utilities Sector (in IDR Million), Cons...",Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8108,NE.GDI.CON.GOVT.CR,GDP expenditure on general government consumpt...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8109,NE.GDI.CON.NPI.CR,GDP expenditure on non profit private institut...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
8110,NE.GDI.CON.PRVT.CR,GDP expenditure on private consumption (in IDR...,Indonesia Database for Policy and Economic Res...,,b'BADAN PUSAT STATISTIK - Statistics Indonesia',,
...,...,...,...,...,...,...,...
8427,NY.GDP.MKTP.CN.AD,GDP: linked series (current LCU),World Development Indicators,GDP at purchaser's prices is the sum of gross ...,b'World Bank staff estimates based on World Ba...,Economy & Growth,
8428,NY.GDP.MKTP.CN.XD,"GDP deflator, period average (LCU index 2000=100)",Africa Development Indicators,The GDP implicit deflator is the ratio of GDP ...,b'World Bank country economists.',,
8429,NY.GDP.MKTP.IN,GDP Deflator,WDI Database Archives,,b'',,
8430,NY.GDP.MKTP.KD,GDP (constant 2010 US$),World Development Indicators,GDP at purchaser's prices is the sum of gross ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8431,NY.GDP.MKTP.KD.87,GDP at market prices (constant 1987 US$),WDI Database Archives,,b'',,
8432,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),World Development Indicators,Annual percentage growth rate of GDP at market...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8433,NY.GDP.MKTP.KN,GDP (constant LCU),World Development Indicators,GDP is the sum of gross value added by all res...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8434,NY.GDP.MKTP.KN.87,GDP at market prices (constant 1987 LCU),WDI Database Archives,,b'',,
8435,NY.GDP.MKTP.KN.87.ZG,GDP growth (annual %),WDI Database Archives,,b'',,
8436,NY.GDP.MKTP.PP.CD,"GDP, PPP (current international $)",World Development Indicators,PPP GDP is gross domestic product converted to...,"b'World Bank, International Comparison Program...",Economy & Growth,
8437,NY.GDP.MKTP.PP.KD,"GDP, PPP (constant 2011 international $)",World Development Indicators,PPP GDP is gross domestic product converted to...,"b'World Bank, International Comparison Program...",Economy & Growth,
8438,NY.GDP.MKTP.PP.KD.87,"GDP, PPP (constant 1987 international $)",WDI Database Archives,,b'',,
8439,NY.GDP.MKTP.XD,"GDP deflator (1987=100,Index)",WDI Database Archives,,b'',,
8440,NY.GDP.MKTP.XU.E,"GDP deflator, end period (base year varies by ...",Africa Development Indicators,The GDP implicit deflator is the ratio of GDP ...,"b'World Bank national accounts data, and OECD ...",,
8443,NY.GDP.PCAP.CD,GDP per capita (current US$),World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8444,NY.GDP.PCAP.CN,GDP per capita (current LCU),World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8445,NY.GDP.PCAP.KD,GDP per capita (constant 2010 US$),World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8446,NY.GDP.PCAP.KD.ZG,GDP per capita growth (annual %),World Development Indicators,Annual percentage growth rate of GDP per capit...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8447,NY.GDP.PCAP.KN,GDP per capita (constant LCU),World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
8448,NY.GDP.PCAP.PP.CD,"GDP per capita, PPP (current international $)",World Development Indicators,GDP per capita based on purchasing power parit...,"b'World Bank, International Comparison Program...",Economy & Growth,
8449,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2011 internation...",World Development Indicators,GDP per capita based on purchasing power parit...,"b'World Bank, International Comparison Program...",Economy & Growth,
8450,NY.GDP.PCAP.PP.KD.87,"GDP per capita, PPP (constant 1987 internation...",WDI Database Archives,,b'',,
8451,NY.GDP.PCAP.PP.KD.ZG,"GDP per capita, PPP annual growth (%)",Africa Development Indicators,Annual percentage growth rate of GDP per capit...,"b'""World Bank, International Comparison Progra...",,
8549,NYGDPMKTPSACD,"GDP,current US$,millions,seas. adj.,",Global Economic Monitor,,b'',,
8550,NYGDPMKTPSACN,"GDP,current LCU,millions,seas. adj.,",Global Economic Monitor,,b'',,
8551,NYGDPMKTPSAKD,"GDP,constant 2010 US$,millions,seas. adj.,",Global Economic Monitor,,b'',,
8552,NYGDPMKTPSAKN,"GDP,constant 2010 LCU,millions,seas. adj.,",Global Economic Monitor,,b'',,
10570,SL.GDP.PCAP.EM.KD,GDP per person employed (constant 2011 PPP $),World Development Indicators,GDP per person employed is gross domestic prod...,"b'International Labour Organization, ILOSTAT d...",Social Protection & Labor,
10571,SL.GDP.PCAP.EM.KD.ZG,GDP per person employed (annual % growth),Africa Development Indicators,GDP per person employed is gross domestic prod...,"b'International Labour Organization, Key Indic...",,
10572,SL.GDP.PCAP.EM.XD,"GDP per person employed, index (1980 = 100)",WDI Database Archives,,b'',,

In [39]:
df = wb.download(indicator='NY.GDP.MKTP.KN', country=['US'], start=1900, end=2018)

In [157]:
us_gdp = df.loc['United States']

In [167]:
us_gdp.index = pd.to_numeric(us_gdp.index)

# Presidents

In [40]:
import pandas as pd

In [43]:
presidents = pd.read_html('https://en.wikipedia.org/wiki/List_of_Presidents_of_the_United_States')

In [52]:
presidents[1].dropna(how='all')

,0,1,2,3,4,5,6,7,8
0,Unaffiliated (2) Federalist (1) Democratic-Rep...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Presidency[a],President,Prior office[b],Party[c],Election,Vice President,NaN,NaN,NaN
2,1,"April 30, 1789[d]–March 4, 1797",NaN,George Washington1732–1799(Lived: 67 years)[3]...,Commander-in-Chiefof theContinental Army(1775–...,NaN,Unaffiliated[2],1788–89,John Adams[e][f]
3,1792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,"March 4, 1797–March 4, 1801",NaN,John Adams1735–1826(Lived: 90 years)[6][7][8],1stVice President of the United States(1789–1797),NaN,Federalist,1796,Thomas Jefferson[g]
5,3,"March 4, 1801–March 4, 1809",NaN,Thomas Jefferson1743–1826(Lived: 83 years)[9][...,2ndVice President of the United States(1797–1801),NaN,Democratic-Republican,1800,"Aaron BurrMarch 4, 1801 – March 4, 1805"
6,1804,"George ClintonMarch 4, 1805 – March 4, 1809",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4,"March 4, 1809–March 4, 1817",NaN,James Madison1751–1836(Lived: 85 years)[12][13...,5thUnited States Secretary of State(1801–1809),NaN,Democratic-Republican,1808,"George ClintonMarch 4, 1809 – April 20, 1812(D..."
8,Office vacant(Balance of Clinton's term),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1812,"Elbridge GerryMarch 4, 1813 – November 23, 181...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Office vacant(Balance of Gerry's term),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5,"March 4, 1817–March 4, 1825",NaN,James Monroe1758–1831(Lived: 73 years)[15][16]...,7thUnited States Secretary of State(1811–1817),NaN,Democratic-Republican,1816,Daniel D. Tompkins
12,1820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6,"March 4, 1825–March 4, 1829",NaN,John Quincy Adams1767–1848(Lived: 80 years)[18...,8thUnited States Secretary of State(1817–1825),NaN,Democratic-Republican,1824,John C. Calhoun
14,7,"March 4, 1829–March 4, 1837",NaN,Andrew Jackson1767–1845(Lived: 78 years)[21][2...,U.S. Senator from Tennessee(1797–1798 & 1823–1...,NaN,Democratic,1828,"John C. Calhoun[h]March 4, 1829 – December 28,..."
15,Office vacant(Balance of Calhoun's term),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1832,"Martin Van BurenMarch 4, 1833 – March 4, 1837",NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,8,"March 4, 1837–March 4, 1841",NaN,Martin Van Buren1782–1862(Lived: 79 years)[24]...,8thVice President of the United States(1833–1837),NaN,Democratic,1836,Richard M. Johnson
18,9,"March 4, 1841–April 4, 1841(Died in office)",NaN,William Henry Harrison1773–1841(Lived: 68 year...,United States Minister to Colombia(1828–1829),NaN,Whig,1840,John Tyler(Succeeded to presidency)
19,10,"April 4, 1841[i]–March 4, 1845",NaN,John Tyler1790–1862(Lived: 71 years)[30][31][32],10thVice President of the United States(1841),NaN,"WhigApril 4, 1841 – September 13, 1841",Office vacant,NaN
20,NaN,"UnaffiliatedSeptember 13, 1841 – March 4, 1845[j]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,11,"March 4, 1845–March 4, 1849",NaN,James K. Polk1795–1849(Lived: 53 years)[33][34...,9thGovernor of Tennessee(1839–1841),NaN,Democratic,1844,George M. Dallas
22,12,"March 4, 1849–July 9, 1850(Died in office)",NaN,Zachary Taylor1784–1850(Lived: 65 years)[36][3...,Major General of the 1st Infantry RegimentUnit...,NaN,Whig,1848,Millard Fillmore(Succeeded to presidency)
23,13,"July 9, 1850[k]–March 4, 1853",NaN,Millard Fillmore1800–1874(Lived: 74 years)[39]...,12thVice President of the United States(1849–1...,NaN,Whig,Office vacant,NaN
24,14,"March 4, 1853–March 4, 1857",NaN,Franklin Pierce1804–1869(Lived: 64 years)[42][...,Brigadier General of the 9th InfantryUnited St...,NaN,Democratic,1852,"William R. KingMarch 4 – April 18, 1853(Died i..."
25,Office vacant(Balance of King's term),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,15,"March 4, 1857–March 4, 1861",NaN,James Buchanan1791–1868(Lived: 77 years)[45][4...,United States Minister to theCourt of St James...,NaN,Democratic,1856,John C. Breckinridge
27,16,"March 4, 1861–April 15, 1865(Died in office)",NaN,Abraham Lincoln1809–1865(Lived: 56 years)[48][...,U.S. Representative for Illinois's 7th Distric...,NaN,Republican(National Union)[l],1860,"Hannibal HamlinMarch 4, 1861 – March 4, 1865"
28,NaN,1864,"Andrew JohnsonMarch 4 – April 15, 1865(Succeed...",NaN,NaN,NaN,NaN,NaN,NaN
29,17,"April 15, 1865–March 4, 1869",NaN,Andrew Johnson1808–1875(Lived: 66 years)[51][5...,16thVice President of the United States(1865),NaN,"National UnionApril 15, 1865 – c. 1868",Office vacant,NaN
...,...,...,...,...,...,...,...,...,...
52,1924,"Charles G. DawesMarch 4, 1925 – March 4, 1929",NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,31,"March 4, 1929–March 4, 1933",NaN,Herbert Hoover1874–1964(Lived: 90 years)[89][9...,3rdUnited States Secretary of Commerce(1921–19...,NaN,Republican,1928,Charles Curtis
54,32,"March 4, 1933–April 12, 1945(Died in office)",NaN,Franklin D. Roosevelt1882–1945(Lived: 63 years...,44thGovernor of New York(1929–1932),NaN,Democratic,1932,"John N. GarnerMarch 4, 1933 – January 20, 1941[p]"
55,1936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,1940,"Henry A. WallaceJanuary 20, 1941 – January 20,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,1944,"Harry S. TrumanJanuary 20 – April 12, 1945(Suc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,33,"April 12, 1945–January 20, 1953",NaN,Harry S. Truman1884–1972(Lived: 88 years)[95][...,34thVice President of the United States(1945),NaN,Democratic,"Office vacantApril 12, 1945 – January 20, 1949",NaN
59,1948,"Alben W. BarkleyJanuary 20, 1949 – January 20,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,34,"January 20, 1953–January 20, 1961",NaN,Dwight D. Eisenhower1890–1969(Lived: 78 years)...,Supreme Allied Commander Europe(1949–1952)(No ...,NaN,Republican,1952,Richard Nixon
61,1956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,35,"January 20, 1961–November 22, 1963(Died in off...",NaN,John F. Kennedy1917–1963(Lived: 46 years)[101]...,U.S. Senator from Massachusetts(1953–1960),NaN,Democratic,1960,Lyndon B. Johnson(Succeeded to presidency)
63,36,"November 22, 1963–January 20, 1969",NaN,Lyndon B. Johnson1908–1973(Lived: 64 years)[10...,37thVice President of the United States(1961–1...,NaN,Democratic,"Office vacantNovember 22, 1963 – January 20, 1965",NaN
64,1964,"Hubert HumphreyJanuary 20, 1965 – January 20, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,37,"January 20, 1969–August 9, 1974(Resigned from ...",NaN,Richard Nixon1913–1994(Lived: 81 years)[106][1...,36thVice President of the United States(1953–1...,NaN,Republican,1968,"Spiro AgnewJanuary 20, 1969 – October 10, 1973..."
66,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,"Office vacantOctober 10 – December 6, 1973",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,"Gerald FordDecember 6, 1973 – August 9, 1974(S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,38,"August 9, 1974–January 20, 1977",NaN,Gerald Ford1913–2006(Lived: 93 years)[109][110...,40thVice President of the United States(1973–1...,NaN,Republican,"Office vacantAugust 9 – December 19, 1974",NaN
70,"Nelson RockefellerDecember 19, 1974 – January ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,39,"January 20, 1977–January 20, 1981",NaN,Jimmy CarterBorn 1924(94 years old)[112][113][...,76thGovernor of Georgia(1971–1975),NaN,Democratic,1976,Walter Mondale
72,40,"January 20, 1981–January 20, 1989",NaN,Ronald Reagan1911–2004(Lived: 93 years)[115][1...,33rdGovernor of California(1967–1975),NaN,Republican,1980,George H. W. Bush
73,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,41,"January 20, 1989–January 20, 1993",NaN,George H. W. Bush1924–2018(Lived: 94 years)[11...,43rdVice President of the United States(1981–1...,NaN,Republican,1988,Dan Quayle
75,42,"January 20, 1993–January 20, 2001",NaN,Bill ClintonBorn 1946(72 years old)[121][122][...,40th & 42ndGovernor of Arkansas(1979–1981 & 19...,NaN,Democratic,1992,Al Gore
76,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,43,"January 20, 2001–January 20, 2009",NaN,George W. BushBorn 1946(72 years old)[124][125],46thGovernor of Texas(1995–2000),NaN,Republican,2000,Dick Cheney
78,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,44,"January 20, 2009–January 20, 2017",NaN,Barack ObamaBorn 1961(57 years old)[126][127],U.S. Senator from Illinois(2005–2008),NaN,Democratic,2008,Joe Biden
80,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,45,"January 20, 2017–Incumbent",NaN,Donald TrumpBorn 1946(72 years old)[128][129],Chairman ofThe Trump Organization(1971–2017)(N...,NaN,Republican,2016,Mike Pence

In [65]:
presidents = pd.read_csv('data/presidents.csv')

In [67]:
presidents = presidents.join(presidents['Unnamed: 1'].str.split('\n–\n', n=2, expand=True))

In [107]:
presidents[0] = presidents[0].str.split('\n', expand=True)[0]

In [109]:
presidents['year'] = pd.to_datetime(presidents[0], format='%B %d, %Y').dt.year

In [115]:
presidents = presidents.dropna(subset=['year'])

In [125]:
presidents = presidents.set_index('year')

In [133]:
presidents = presidents[~presidents.index.duplicated(keep='last')]

In [ ]:
presidents.index = presidents.index.astype(int)

In [143]:
presidents = presidents.reindex(range(presidents.index.min(), 2019), method='ffill')

In [144]:
presidents.head()

,Presidency[a],Unnamed: 1,President,Unnamed: 3,Prior office[b],Party[c],Unnamed: 6,Election,Vice President,0,1
year,,,,,,,,,,,
1789,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,Unaffiliated\n[2],1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797"
1790,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,Unaffiliated\n[2],1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797"
1791,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,Unaffiliated\n[2],1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797"
1792,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,Unaffiliated\n[2],1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797"
1793,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,Unaffiliated\n[2],1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797"

In [152]:
presidents['Unnamed: 6'] = pd.to_numeric(presidents['Unnamed: 6'].replace({'Republican': 1, 'Democratic':-1}), errors='coerse')

In [158]:
presidents.join(us_gdp)

,Presidency[a],Unnamed: 1,President,Unnamed: 3,Prior office[b],Party[c],Unnamed: 6,Election,Vice President,0,1,NY.GDP.MKTP.KN
year,,,,,,,,,,,,
1789,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1790,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1791,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1792,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1793,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1794,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1795,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1796,1.0,"April 30, 1789\n[d]\n–\nMarch 4, 1797",NaN,George Washington\n1732–1799\n(Lived: 67 years...,Commander-in-Chief\nof the\nContinental Army\n...,NaN,NaN,1788–89,John Adams\n[e][f],"April 30, 1789","March 4, 1797",NaN
1797,2.0,"March 4, 1797\n–\nMarch 4, 1801",NaN,John Adams\n1735–1826\n(Lived: 90 years)\n[6][...,1st\nVice President of the United States\n(178...,NaN,NaN,1796,Thomas Jefferson\n[g],"March 4, 1797","March 4, 1801",NaN
1798,2.0,"March 4, 1797\n–\nMarch 4, 1801",NaN,John Adams\n1735–1826\n(Lived: 90 years)\n[6][...,1st\nVice President of the United States\n(178...,NaN,NaN,1796,Thomas Jefferson\n[g],"March 4, 1797","March 4, 1801",NaN
1799,2.0,"March 4, 1797\n–\nMarch 4, 1801",NaN,John Adams\n1735–1826\n(Lived: 90 years)\n[6][...,1st\nVice President of the United States\n(178...,NaN,NaN,1796,Thomas Jefferson\n[g],"March 4, 1797","March 4, 1801",NaN
1800,2.0,"March 4, 1797\n–\nMarch 4, 1801",NaN,John Adams\n1735–1826\n(Lived: 90 years)\n[6][...,1st\nVice President of the United States\n(178...,NaN,NaN,1796,Thomas Jefferson\n[g],"March 4, 1797","March 4, 1801",NaN
1801,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1802,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1803,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1804,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1805,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1806,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1807,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1808,3.0,"March 4, 1801\n–\nMarch 4, 1809",NaN,Thomas Jefferson\n1743–1826\n(Lived: 83 years)...,2nd\nVice President of the United States\n(179...,NaN,NaN,1800,"Aaron Burr\nMarch 4, 1801 – March 4, 1805","March 4, 1801","March 4, 1809",NaN
1809,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1810,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1811,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1812,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1813,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1814,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1815,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1816,4.0,"March 4, 1809\n–\nMarch 4, 1817",NaN,James Madison\n1751–1836\n(Lived: 85 years)\n[...,5th\nUnited States Secretary of State\n(1801–1...,NaN,NaN,1808,"George Clinton\nMarch 4, 1809 – April 20, 1812...","March 4, 1809","March 4, 1817",NaN
1817,5.0,"March 4, 1817\n–\nMarch 4, 1825",NaN,James Monroe\n1758–1831\n(Lived: 73 years)\n[1...,7th\nUnited States Secretary of State\n(1811–1...,NaN,NaN,1816,Daniel D. Tompkins,"March 4, 1817","March 4, 1825",NaN
1818,5.0,"March 4, 1817\n–\nMarch 4, 1825",NaN,James Monroe\n1758–1831\n(Lived: 73 years)\n[1...,7th\nUnited States Secretary of State\n(1811–1...,NaN,NaN,1816,Daniel D. Tompkins,"March 4, 1817","March 4, 1825",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1989,41.0,"January 20, 1989\n–\nJanuary 20, 1993",NaN,George H. W. Bush\n1924–2018\n(Lived: 94 years...,43rd\nVice President of the United States\n(19...,NaN,1.0,1988,Dan Quayle,"January 20, 1989","January 20, 1993",NaN
1990,41.0,"January 20, 1989\n–\nJanuary 20, 1993",NaN,George H. W. Bush\n1924–2018\n(Lived: 94 years...,43rd\nVice President of the United States\n(19...,NaN,1.0,1988,Dan Quayle,"January 20, 1989","January 20, 1993",NaN
1991,41.0,"January 20, 1989\n–\nJanuary 20, 1993",NaN,George H. W. Bush\n1924–2018\n(Lived: 94 years...,43rd\nVice President of the United States\n(19...,NaN,1.0,1988,Dan Quayle,"January 20, 1989","January 20, 1993",NaN
1992,41.0,"January 20, 1989\n–\nJanuary 20, 1993",NaN,George H. W. Bush\n1924–2018\n(Lived: 94 years...,43rd\nVice President of the United States\n(19...,NaN,1.0,1988,Dan Quayle,"January 20, 1989","January 20, 1993",NaN
1993,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1994,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1995,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1996,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1997,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1998,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
1999,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
2000,42.0,"January 20, 1993\n–\nJanuary 20, 2001",NaN,Bill Clinton\nBorn 1946\n(72 years old)\n[121]...,40th & 42nd\nGovernor of Arkansas\n(1979–1981 ...,NaN,-1.0,1992,Al Gore,"January 20, 1993","January 20, 2001",NaN
2001,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2002,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2003,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2004,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2005,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2006,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2007,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2008,43.0,"January 20, 2001\n–\nJanuary 20, 2009",NaN,George W. Bush\nBorn 1946\n(72 years old)\n[12...,46th\nGovernor of Texas\n(1995–2000),NaN,1.0,2000,Dick Cheney,"January 20, 2001","January 20, 2009",NaN
2009,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2010,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2011,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2012,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2013,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2014,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2015,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2016,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",NaN
2017,45.0,"January 20, 2017\n–\nIncumbent",NaN,Donald Trump\nBorn 1946\n(72 years old)\n[128]...,Chairman of\nThe Trump Organization\n(1971–201...,NaN,1.0,2016,Mike Pence,"January 20, 2017",Incumbent,NaN
2018,45.0,"January 20, 2017\n–\nIncumbent",NaN,Donald Trump\nBorn 1946\n(72 years old)\n[128]...,Chairman of\nThe Trump Organization\n(1971–201...,NaN,1.0,2016,Mike Pence,"January 20, 2017",Incumbent,NaN

In [168]:
presidents['gdp'] = us_gdp

In [176]:
presidents.tail()

,Presidency[a],Unnamed: 1,President,Unnamed: 3,Prior office[b],Party[c],Unnamed: 6,Election,Vice President,0,1,gdp,gdp_diff,gdp_diff_diff
year,,,,,,,,,,,,,,
2014,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",1.620886e+13,1.028616,0.986620
2015,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",1.667269e+13,1.014853,1.007765
2016,44.0,"January 20, 2009\n–\nJanuary 20, 2017",NaN,Barack Obama\nBorn 1961\n(57 years old)\n[126]...,U.S. Senator from Illinois\n(2005–2008),NaN,-1.0,2008,Joe Biden,"January 20, 2009","January 20, 2017",1.692033e+13,1.022733,NaN
2017,45.0,"January 20, 2017\n–\nIncumbent",NaN,Donald Trump\nBorn 1946\n(72 years old)\n[128]...,Chairman of\nThe Trump Organization\n(1971–201...,NaN,1.0,2016,Mike Pence,"January 20, 2017",Incumbent,1.730498e+13,NaN,NaN
2018,45.0,"January 20, 2017\n–\nIncumbent",NaN,Donald Trump\nBorn 1946\n(72 years old)\n[128]...,Chairman of\nThe Trump Organization\n(1971–201...,NaN,1.0,2016,Mike Pence,"January 20, 2017",Incumbent,NaN,NaN,NaN

In [172]:
presidents['gdp_diff'] = presidents['gdp'].shift(-1)/presidents['gdp']

In [173]:
presidents['gdp_diff_diff'] = presidents['gdp_diff'].shift(-1)/presidents['gdp_diff']

In [175]:
presidents['Unnamed: 6'].corr(presidents['gdp_diff_diff'])

0.2376064871310884